openapi: 3.0.3
info:
  title: 'IClinic Chalenge API'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/prescriptions:
    post:
      summary: 'Store a new prescription.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clinic:
                  type: integer
                  description: ''
                  example: 6
                physician:
                  type: integer
                  description: ''
                  example: 16
                patient:
                  type: integer
                  description: ''
                  example: 11
                text:
                  type: string
                  description: 'Must be at least 5 characters. Must not be greater than 9999 characters.'
                  example: 'Dipirona 1x ao dia.'
              required:
                - physician
                - patient
                - text
      security: []
tags:
  -
    name: Endpoints
    description: ''
